# Generated by Django 4.1.7 on 2023-07-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0002_remove_student_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
