# Generated by Django 4.1.7 on 2023-07-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0003_student_reg_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('head_of_departmemt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_api.department')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='students_api.courses'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='students_api.department'),
        ),
    ]
