# Generated by Django 4.1.7 on 2023-07-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0004_department_courses_student_course_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='students_api.courses'),
        ),
    ]
