# Generated by Django 4.1.7 on 2023-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0005_remove_student_course_alter_student_field_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(choices=[('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters'), ('PHD', 'PhD')], default='', max_length=100),
        ),
    ]
