# Generated by Django 4.1.7 on 2023-07-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0006_courses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students_api.department'),
        ),
    ]
