# Generated by Django 4.1.7 on 2023-07-11 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0008_alter_courses_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students_api.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students_api.courses'),
        ),
    ]
