# Generated by Django 4.1.7 on 2023-07-11 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0009_alter_student_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.CharField(choices=[('FORM 1', 'Form 1'), ('FORM 2', 'Form 2'), ('FORM 3', 'Form 3'), ('FORM 4', 'Form 4')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 13, 42, 23, 939153, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
