# Generated by Django 4.1.7 on 2023-07-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0010_remove_student_department_remove_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('combinations', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_api.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
