# Generated by Django 4.1.7 on 2023-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0011_teacher_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('happening_date', models.DateField()),
            ],
        ),
    ]
