# Generated by Django 4.1.7 on 2023-07-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0013_classteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='stream',
            field=models.CharField(choices=[('P', 'P'), ('R', 'R'), ('S', 'S'), ('T', 'T')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('P', 'P'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=50, null=True),
        ),
    ]
